# Generated by Django 5.2.3 on 2025-06-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField()),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField()),
                ('gender', models.CharField()),
            ],
        ),
    ]
